# docker-compose.yml

# Use root/example as user/password credentials
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nest-study-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cj123456  
      MYSQL_DATABASE: test
    ports:
      - 3307:3306
    volumes:
      - F:/docker/data:/var/lib/mysql   

  # navicat(数据库管理工具)
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
   # Redis 服务
  redis:
    image: redis:latest
    container_name: nest-study-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data    
volumes:
  redis-data:
